spring:
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://db4free.net:3306/synpasisproject?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: itoguiii
        password: itoguiii
        testWhileIdle: true
        validationQuery: SELECT 1
    jpa:
        database: MYSQL
        show-sql: true
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
    application:
        name: resource-synapsis-project
server:
  port: 8081
